[env:megaatmega2560_scanner]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

src_filter = +<../examples/soft_scanner.cpp>

[env:megaatmega2560_main]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 4-20ma/ModbusMaster @ ^2.0.1

