[env:megaatmega2560_scanner]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

src_filter = +<../examples/soft_scanner.cpp>

[env:megaatmega2560_main]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps = 
    4-20ma/ModbusMaster @ ^2.0.1
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    adafruit/Adafruit MAX31855 library @ ^1.4.0
    adafruit/Adafruit MCP4725 @ ^2.0.0
    br3ttb/PID @ ^1.2.1
    bblanchon/ArduinoJson @ ^6.21.3
    bogde/HX711 @ ^0.7.5


